site_name: ${{values.uid}}
site_description: "${{values.name}} that displays grettings."
repo_url: https://github.com/lucilegabriellefievetlacombe-afk/${{values.uid}}
edit_uri: edit/main/docs

plugins:
  - techdocs-core

# For sidebar navigation on https://backstage.io/, see `microsite/sidebars.json`
nav:
  - Overview:
      - Getting started: 'docs/index.md'