name: cicd

on:
  push:
    paths:
      - src/**
    branches:
      - 'pocs/[A-Z]+-[A-Z]+-[A-Z]+-[a-z]?'
      - 'features/[A-Z]+-[A-Z]+-[A-Z]+-[a-z]?'
      - 'hardenings/[A-Z]+-[A-Z]+-[A-Z]+-[a-z]?'
      - 'fix/[A-Z]+-[A-Z]+-[A-Z]+-[a-z]?'
      - 'hotfix/[A-Z]+-[A-Z]+-[A-Z]+-[a-z]?'
      - 'refactos/[A-Z]+-[A-Z]+-[A-Z]+-[a-z]?'
      - 'releases/[0-9]+.[0-9]+.[0-9]+'
      - 'hardenings/[0-9]+.[0-9]+.[0-9]+'
      - develop
      - main
      - my_course_**
      - 'v[0-9]+.[0-9]+.[0-9]+'
      - '!releases/**-alpha'
      - '!**wip'
      - '!**WIP'

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:

      - name: Shorten commit id
        shell: bash
        run: |
          github_sha_hash=${{ github.sha }}
          github_sha_short="${github_sha_hash:0:7}"
          echo "COMMIT_ID=${github_sha_short}" >> "$GITHUB_ENV"

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: luspokvenus/python-app:${{ env.COMMIT_ID }}

    outputs:
      commit_id: ${{ env.COMMIT_ID }}

  cd:
    needs: ci
    runs-on: self-hosted
    steps:
      - name: Check shorten commit id output
        shell: bash
        run: |
          echo ${{needs.ci.outputs.commit_id}}

      - uses: actions/checkout@v3

      - name: Modify our python app chart values file
        shell: bash
        run : |
          sed -i 's/tag: ".*"/tag: "${{needs.ci.outputs.commit_id}}"/' charts/python-app/values.yaml

      - name: Commit Changes
        uses: EndBug/add-and-commit@v9
        with:
          message: 'upated image version for python-app chart ${{needs.ci.outputs.commit_id}}'

      - name: Install argocd on our self runner
        shell: bash
        run: |
          curl -ksSL -o argocd https://argocd-server.argocd/download/argocd-linux-amd64
          chmod +x argocd
          sudo mv ./argocd /usr/local/bin/argocd

      - name: Argocd app sync
        shell: bash
        run: |
          argocd login argocd-server.argocd \
            --insecure  \
            --grpc-web \
            --username admin \
            --password  ${{ secrets.ARGOCD_PASSWORD }}
          argocd account get-user-info
          argocd app sync pyhton-app

