name:  ${{values.uid}}-cicd

on:
  push:
    paths:
      - src/**
    branches:
      - 'poc/[A-Z]+-[A-Z]+-[A-Z]+-[a-z]?[0-9]+'
      - 'feature/[A-Z]+-[A-Z]+-[A-Z]+-[a-z]?[0-9]+'
      - 'fix/[A-Z]+-[A-Z]+-[A-Z]+-[a-z]?[0-9]+'
      - 'hotfix/[A-Z]+-[A-Z]+-[A-Z]+-[a-z]?[0-9]+'
      - 'refacto/[A-Z]+-[A-Z]+-[A-Z]+-[a-z]?[0-9]+'
      - 'security/[A-Z]+-[A-Z]+-[A-Z]+-[a-z]?[0-9]+'
      - 'ci/[A-Z]+-[A-Z]+-[A-Z]+-[a-z]?[0-9]+'
      - 'test/[A-Z]+-[A-Z]+-[A-Z]+-[a-z]?[0-9]+'
      - 'dependabot/*'
      - 'renovate/*'
      - 'perf/[A-Z]+-[A-Z]+-[A-Z]+-[a-z]?[0-9]+'
      - 'chlore/[A-Z]+-[A-Z]+-[A-Z]+-[a-z]?[0-9]+'
      - develop
      - 'release/[0-9]+.[0-9]+-alpha'
      - 'release/[0-9]+.[0-9]+.[0-9]+'
      - 'security/[0-9]+.[0-9]+.[0-9]+'
      - 'perf/[0-9]+.[0-9]+.[0-9]+'
      - main
      - my_course_**
      - '!docs/[A-Z]+-[A-Z]+-[A-Z]+-[a-z]?'
      - '!**wip'
      - '!**WIP'
      - '!**Wip'

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:

      - name: Shorten commit id
        shell: bash
        run: |
          github_sha_hash=${{'${{ github.sha }}'}}
          github_sha_short="${{'${github_sha_hash:0:7}'}}"
          echo "COMMIT_ID=${github_sha_short}" >> "$GITHUB_ENV"

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{'${{ secrets.DOCKERHUB_USERNAME }}'}}
          password: ${{'${{ secrets.DOCKERHUB_TOKEN }}'}}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: luspokvenus/${{values.uid}}:${{'${{ env.COMMIT_ID }}'}}

    outputs:
      commit_id: ${{'${{ env.COMMIT_ID }}'}}

  cd:
    needs: ci
    runs-on: self-hosted
    steps:
      - name: Check shorten commit id output
        shell: bash
        run: |
          echo ${{'${{needs.ci.outputs.commit_id}}'}}'

      - uses: actions/checkout@v3

      - name: Modify our python app chart values file
        shell: bash
        run : |
          sed -i 's/tag: ".*"/tag: "${{'${{needs.ci.outputs.commit_id}}'}}"/' charts/${{values.uid}}/values.yaml
          sed -i 's/tag: ".*"/tag: "${{'${{needs.ci.outputs.commit_id}}'}}"/' charts/${{values.uid}}/values-${{values.uid}}-dev.yaml
          sed -i 's/tag: ".*"/tag: "${{'${{needs.ci.outputs.commit_id}}'}}"/' charts/${{values.uid}}/values-${{values.uid}}-qual.yaml
          sed -i 's/tag: ".*"/tag: "${{'${{needs.ci.outputs.commit_id}}'}}"/' charts/${{values.uid}}/values-${{values.uid}}-ppd.yaml
          sed -i 's/tag: ".*"/tag: "${{'${{needs.ci.outputs.commit_id}}'}}"/' charts/${{values.uid}}/values-${{values.uid}}-dev.yaml

      - name: Commit Changes
        uses: EndBug/add-and-commit@v9
        with:
          message: "upated image version for ${{values.uid}} chart ${{'${{needs.ci.outputs.commit_id}}'}} commit id"

      - name: Install argocd on our self runner
        shell: bash
        run: |
          curl -ksSL -o argocd https://argocd-server.argocd/download/argocd-linux-amd64
          chmod +x argocd
          sudo mv ./argocd /usr/local/bin/argocd

      - name: Argocd app sync
        shell: bash
        run: |
          argocd login argocd-server.argocd \
            --insecure  \
            --grpc-web \
            --username admin \
            --password  ${{'${{ secrets.ARGOCD_PASSWORD }}'}}
          argocd account get-user-info
          argocd app sync pyhton-app
      
      - name: Ensure evolutions argocd repo and app
        shell: bash
        run: |

          # Connects the argocd repo
          repo="https://github.com/luspokvenus/${{values.uid}}.git"
          argocd repo list | grep -q $repo || argocd repo add $repo

          # Creates the argocd app
          argocd app get ${{values.uid}} || argocd app create ${{values.uid}} \
            --repo $repo \
            --path charts/${{values.uid}} \
            --dest-namespace ${{'${{ env.GITHUB_ACTOR_ID }}'}}_${{'${{ env.GITHUB_REF_NAME}}'}} \
            --dest-server https://kubernetes.default.svc \
            --values values-${{values.uid}}-dev.yaml \
            --revision ${{'${{ env.GITHUB_BASE_REF}}'}}_${{'${{ env.GITHUB_ACTOR_ID }}'}}_${{'${{ env.GITHUB_REF_NAME}}'}}_${{'${{ env.COMMIT_ID }}'}}\
            --sync-policy manual \
            --sync-option CreateNamespace=true
        on:
          branches:
            - 'poc/[A-Z]+-[A-Z]+-[A-Z]+-[a-z]?[0-9]+'
            - 'feature/[A-Z]+-[A-Z]+-[A-Z]+-[a-z]?[0-9]+'
            - 'fix/[A-Z]+-[A-Z]+-[A-Z]+-[a-z]?[0-9]+'
            - 'refacto/[A-Z]+-[A-Z]+-[A-Z]+-[a-z]?[0-9]+'
            - 'security/[A-Z]+-[A-Z]+-[A-Z]+-[a-z]?[0-9]+'
            - 'ci/[A-Z]+-[A-Z]+-[A-Z]+-[a-z]?[0-9]+'
            - 'test/[A-Z]+-[A-Z]+-[A-Z]+-[a-z]?[0-9]+'
            - 'dependabot/*'
            - 'renovate/*'
            - 'perf/[A-Z]+-[A-Z]+-[A-Z]+-[a-z]?[0-9]+'
            - 'chlore/[A-Z]+-[A-Z]+-[A-Z]+-[a-z]?[0-9]+'
      

      - name: Ensure DEV argocd repo and app
        shell: bash
        run: |

          # Connects the argocd repo
          repo="https://github.com/luspokvenus/${{values.uid}}.git"
          argocd repo list | grep -q $repo || argocd repo add $repo

          # Creates the argocd app
          argocd app get ${{values.uid}} || argocd app create ${{values.uid}} \
            --repo $repo \
            --path charts/${{values.uid}} \
            --dest-namespace qual \
            --dest-server https://kubernetes.default.svc \
            --values values-${{values.uid}}-qual.yaml \
            --revision  ${{'${{ env.GITHUB_REF_NAME}}'}}_${{'${{ env.GITHUB_BASE_REF}}'}}_${{'${{ env.COMMIT_ID }}\
            --sync-policy manual \
            --sync-option CreateNamespace=true
        on:
          branches:
            - develop

      - name: Ensure PPD argocd repo and app
        shell: bash
        run: |

          # Connects the argocd repo
          repo="https://github.com/luspokvenus/${{values.uid}}.git"
          argocd repo list | grep -q $repo || argocd repo add $repo

          # Creates the argocd app
          argocd app get ${{values.uid}} || argocd app create ${{values.uid}} \
            --repo $repo \
            --path charts/${{values.uid}} \
            --dest-namespace ppd \
            --dest-server https://kubernetes.default.svc \
            --values values-${{values.uid}}-ppd.yaml \
            --revision ${{'${{ env.GITHUB_REF_NAME}}'}}_${{'${{ env.GITHUB_BASE_REF}}'}}_${{'${{ env.COMMIT_ID }}\
            --sync-policy manual \
            --sync-option CreateNamespace=true
        on:
          branches:
            - 'release/**'
            - 'hotfix/[A-Z]+-[A-Z]+-[A-Z]+-[a-z]?[0-9]+'
            - 'security/[0-9]+.[0-9]+.[0-9]+'
            - 'perf/[0-9]+.[0-9]+.[0-9]+'

      - name: Ensure PROD argocd repo and app
        shell: bash
        run: |

          # Connects the argocd repo
          repo="https://github.com/luspokvenus/${{values.uid}}.git"
          argocd repo list | grep -q $repo || argocd repo add $repo

          # Creates the argocd app
          argocd app get ${{values.uid}} || argocd app create ${{values.uid}} \
            --repo $repo \
            --path charts/${{values.uid}} \
            --dest-namespace prod \
            --dest-server https://kubernetes.default.svc \
            --values values-${{values.uid}}-prod.yaml \
            --revision ${{'${{ env.GITHUB_BASE_REF}}'}} \
            --sync-policy manual \
            --sync-option CreateNamespace=true
        on:
          branches:
            - main

      - name: Argocd app sync
        shell: bash
        run: |
          argocd app sync ${{values.uid}}
          argocd app wait ${{values.uid}} --timeout 180
